execute:
  freeze: auto
  
project:
  type: book
  output-dir: ../docs

book:
  title: "Property Taxes in Cook County"
  subtitle: "Supplementary Data & Analysis"
  author: "Alea Wilbur-Mujtaba & Michael Van Hulle"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Exemption Whitepaper"
      chapters:
        - exemp_report_2021.qmd
        - exemp_report_2022.qmd
        - exemp_report_2023.qmd
    - part: "Exemption Addendum"
      chapters:
        - exemption_addendum_2021.qmd
        - exemption_addendum_2022.qmd
        - exemption_addendum_2023.qmd
    - part: "Incentives Report"
      chapters:
        - incentive_report_yearlytrends.qmd
        - incentives_report_2021.qmd
        - incentives_report_2022.qmd
        - incentives_report_2023.qmd
        # - incentive_report_template.qmd
  #  - part: "Additional Analysis"
#      chapters:
       #   - takeup_rate?
       #   - senior freeze     # combined senior_freeze and senior_freeze_lostexemptions
       #   - frequently_asked_questions.qmd
       


  navbar: 
    search: true
    left: 
      - text: "Exemption Whitepaper"
        menu:
          - exemp_report_2021.qmd
          - exemp_report_2022.qmd
          - exemp_report_2023.qmd
      - text: "Exemption Addendum"
        menu:
          - exemption_addendum_2021.qmd
          - exemption_addendum_2022.qmd
          - exemption_addendum_2023.qmd
      - text: "Incentives Report"
        menu:
          - incentive_report_yearlytrends.qmd
          - incentives_report_2021.qmd
          - incentives_report_2022.qmd
          - incentives_report_2023.qmd
    right: 
      - icon: github
        href: https://github.com/uic-gfrc/CookCounty-PropertyTaxes.git


format:
  html:
    theme: 
      light: lightly
      dark: darkly
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    code-overflow: wrap
    code-copy: true
    fig-cap-location: top
    tbl-cap-location: top
    df-print: paged
    number-sections: false


